var searchData=
[
  ['label_20lv_5flabel_0',['Label (lv_label)',['../md_components_2lvgl_2docs_2widgets_2core_2label.html',1,'']]],
  ['layers_1',['Layers',['../md_components_2lvgl_2docs_2overview_2layer.html',1,'']]],
  ['layouts_2',['layouts',['../md_components_2lvgl_2docs_2layouts_2index.html',1,'Layouts'],['../md_components_2lvgl_2docs_2overview_2coords.html',1,'Positions, sizes, and layouts']]],
  ['led_20lv_5fled_3',['LED (lv_led)',['../md_components_2lvgl_2docs_2widgets_2extra_2led.html',1,'']]],
  ['libraries_4',['3rd party libraries',['../md_components_2lvgl_2docs_2libs_2index.html',1,'']]],
  ['line_20lv_5fline_5',['Line (lv_line)',['../md_components_2lvgl_2docs_2widgets_2core_2line.html',1,'']]],
  ['list_6',['Todo List',['../todo.html',1,'']]],
  ['list_20lv_5fdropdown_7',['Drop-down list (lv_dropdown)',['../md_components_2lvgl_2docs_2widgets_2core_2dropdown.html',1,'']]],
  ['list_20lv_5flist_8',['List (lv_list)',['../md_components_2lvgl_2docs_2widgets_2extra_2list.html',1,'']]],
  ['logging_9',['Logging',['../md_components_2lvgl_2docs_2porting_2log.html',1,'']]],
  ['lottie_20player_10',['Lottie player',['../md_components_2lvgl_2docs_2libs_2rlottie.html',1,'']]],
  ['lv_5fanimimg_11',['Animation Image (lv_animimg)',['../md_components_2lvgl_2docs_2widgets_2extra_2animimg.html',1,'']]],
  ['lv_5farc_12',['Arc (lv_arc)',['../md_components_2lvgl_2docs_2widgets_2core_2arc.html',1,'']]],
  ['lv_5fbar_13',['Bar (lv_bar)',['../md_components_2lvgl_2docs_2widgets_2core_2bar.html',1,'']]],
  ['lv_5fbtn_14',['Button (lv_btn)',['../md_components_2lvgl_2docs_2widgets_2core_2btn.html',1,'']]],
  ['lv_5fbtnmatrix_15',['Button matrix (lv_btnmatrix)',['../md_components_2lvgl_2docs_2widgets_2core_2btnmatrix.html',1,'']]],
  ['lv_5fcalendar_16',['Calendar (lv_calendar)',['../md_components_2lvgl_2docs_2widgets_2extra_2calendar.html',1,'']]],
  ['lv_5fcanvas_17',['Canvas (lv_canvas)',['../md_components_2lvgl_2docs_2widgets_2core_2canvas.html',1,'']]],
  ['lv_5fchart_18',['Chart (lv_chart)',['../md_components_2lvgl_2docs_2widgets_2extra_2chart.html',1,'']]],
  ['lv_5fcheckbox_19',['Checkbox (lv_checkbox)',['../md_components_2lvgl_2docs_2widgets_2core_2checkbox.html',1,'']]],
  ['lv_5fcolorwheel_20',['Color wheel (lv_colorwheel)',['../md_components_2lvgl_2docs_2widgets_2extra_2colorwheel.html',1,'']]],
  ['lv_5fdropdown_21',['Drop-down list (lv_dropdown)',['../md_components_2lvgl_2docs_2widgets_2core_2dropdown.html',1,'']]],
  ['lv_5fimg_22',['Image (lv_img)',['../md_components_2lvgl_2docs_2widgets_2core_2img.html',1,'']]],
  ['lv_5fimgbtn_23',['Image button (lv_imgbtn)',['../md_components_2lvgl_2docs_2widgets_2extra_2imgbtn.html',1,'']]],
  ['lv_5fkeyboard_24',['Keyboard (lv_keyboard)',['../md_components_2lvgl_2docs_2widgets_2extra_2keyboard.html',1,'']]],
  ['lv_5flabel_25',['Label (lv_label)',['../md_components_2lvgl_2docs_2widgets_2core_2label.html',1,'']]],
  ['lv_5fled_26',['LED (lv_led)',['../md_components_2lvgl_2docs_2widgets_2extra_2led.html',1,'']]],
  ['lv_5fline_27',['Line (lv_line)',['../md_components_2lvgl_2docs_2widgets_2core_2line.html',1,'']]],
  ['lv_5flist_28',['List (lv_list)',['../md_components_2lvgl_2docs_2widgets_2extra_2list.html',1,'']]],
  ['lv_5fmenu_29',['Menu (lv_menu)',['../md_components_2lvgl_2docs_2widgets_2extra_2menu.html',1,'']]],
  ['lv_5fmeter_30',['Meter (lv_meter)',['../md_components_2lvgl_2docs_2widgets_2extra_2meter.html',1,'']]],
  ['lv_5fmsgbox_31',['Message box (lv_msgbox)',['../md_components_2lvgl_2docs_2widgets_2extra_2msgbox.html',1,'']]],
  ['lv_5fobj_32',['Base object (lv_obj)',['../md_components_2lvgl_2docs_2widgets_2obj.html',1,'']]],
  ['lv_5froller_33',['Roller (lv_roller)',['../md_components_2lvgl_2docs_2widgets_2core_2roller.html',1,'']]],
  ['lv_5fslider_34',['Slider (lv_slider)',['../md_components_2lvgl_2docs_2widgets_2core_2slider.html',1,'']]],
  ['lv_5fspan_35',['Span (lv_span)',['../md_components_2lvgl_2docs_2widgets_2extra_2span.html',1,'']]],
  ['lv_5fspinbox_36',['Spinbox (lv_spinbox)',['../md_components_2lvgl_2docs_2widgets_2extra_2spinbox.html',1,'']]],
  ['lv_5fspinner_37',['Spinner (lv_spinner)',['../md_components_2lvgl_2docs_2widgets_2extra_2spinner.html',1,'']]],
  ['lv_5fswitch_38',['Switch (lv_switch)',['../md_components_2lvgl_2docs_2widgets_2core_2switch.html',1,'']]],
  ['lv_5ftable_39',['Table (lv_table)',['../md_components_2lvgl_2docs_2widgets_2core_2table.html',1,'']]],
  ['lv_5ftabview_40',['Tabview (lv_tabview)',['../md_components_2lvgl_2docs_2widgets_2extra_2tabview.html',1,'']]],
  ['lv_5ftextarea_41',['Text area (lv_textarea)',['../md_components_2lvgl_2docs_2widgets_2core_2textarea.html',1,'']]],
  ['lv_5ftileview_42',['Tile view (lv_tileview)',['../md_components_2lvgl_2docs_2widgets_2extra_2tileview.html',1,'']]],
  ['lv_5fwin_43',['Window (lv_win)',['../md_components_2lvgl_2docs_2widgets_2extra_2win.html',1,'']]]
];
